### ISSUE TITLE
Multiple service_name for a certificate

### ISSUE THREAD

**Issue by albatros69** [Spredzy/lecm#32]
It would be great to be able to restart more than one service upon renewal of a certificate (like a webserver and a MTA).

**Comment by Spredzy** [comment]
Hello @albatros69,

Just to make sure I understand this query correclty, what you want is that for a single certificate, one can reload several services, is that correct?

Something like:

```
certificates:
  foo.example.org:
    service_name:
      - httpd
      - postfix
```
